### ISSUE TITLE
Right to Left slide menu not opening after DsiplayAlert

### ISSUE THREAD

**Issue by sylendra7** [XAM-Consulting/SlideOverKit#108]
The slide menu is not opening after showing DisplayAlert in iOS . After closing the  DisplayAlert if I try to open a menu .then grayscale is showing.

**Comment by rmoscat** [comment]
Hi,
sylendra7

When an AlertDialog is presented, the "SlideMenuView" is not show when in "this.IsFullScreen = true;" mode

Solutions: I had to apply a fix to the code so that it could work for me. replace at the source SlideOverKitiOSHandler.cs where they are "UIApplication.SharedApplication.KeyWindow" with "UIApplication.SharedApplication.Delegate.GetWindow ()"

I applied the previous fix and it worked. let me know if it works for you.

Good luck.

**Comment by sylendra7** [comment]
Hi ,

@rmoscat  Thank you very much it was fixed ...

--Kind Regards
Sylendra
