### ISSUE TITLE
Slideup menu is not displayed on iPhone 6

### ISSUE THREAD

**Issue by escamoteur** [XAM-Consulting/SlideOverKit#11]
Hi,

this might sound strange, but on two iPhone 6 of testers of my App the menu is not displayed when called ShowMenu.

Have you tested on iPhone 6
Best
Thomas

**Comment by rid00z** [comment]
Is this only the SlideUpMenu?

**Comment by rid00z** [comment]
I'm wondering if this solves your issue: https://github.com/XAM-Consulting/SlideOverKit/commit/9ee34977e9fc5e564b72724020bf5af44ba75578

You can just put that code into your iOS project. 

`var mc = new MenuContainerPageiOSRenderer ();`

**Comment by escamoteur** [comment]
I only use slideup at the moment. Strange thing is that it works on iPhone 5

**Comment by escamoteur** [comment]
Hi Michael,

it's hard to believe, but my testers just told me that it know works.
Do you have any idea why it could work on iPhone5 but not 6?

Thanks
Thomas

**Comment by ryanspiffy** [comment]
We ran into this same issue.  The SlideOverKit worked fine for a dev build, but a release build had the linker error and the menu was not working on the iPhone6 and newer.  We added the one line to our iOS project and it fixed the linker error.

**Comment by Ingenator** [comment]
Hey there,

I'm experiencing the same issue only with testflight builds on iphone 6 and newer, iphone 5 works perfectly.

**Comment by mick1313** [comment]
> You can just put that code into your iOS project.
> var mc = new MenuContainerPageiOSRenderer ();

Confused.  Where do you add that in the IOS project?  Just anywhere?

**Comment by ryanspiffy** [comment]
We have it in our AppDelegate.cs.  The variable isn’t used, it’s merely a
work around.  The idea is that with that line, you have a hard reference to
the object, which forces the linker to include the needed entries.

On November 4, 2016 at 1:38:03 AM, MIckey Keenan (notifications@github.com)
wrote:

You can just put that code into your iOS project.
var mc = new MenuContainerPageiOSRenderer ();

Confused. Where do you add that in the IOS project? Just anywhere?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/XAM-Consulting/SlideOverKit/issues/11#issuecomment-258349019>,
or mute the thread

**Comment by alecmontgomery** [comment]
I was experiencing this same issue and @rid00z 's solution of adding 

`var mc = new MenuContainerPageiOSRenderer ();` fixed it. I added it to the iOS `AppDelegate` file. You will need to import the SlideOverKit.iOS namespace.

**Comment by deepaksakpal** [comment]
the solution recommended above didn't work for me on iOS but works on Android. Following is the code for Menu screen:

            this.IsFullScreen = true;
            var size = Plugin.XamJam.Screen.CrossScreen.Current.Size;
            this.WidthRequest = size.Width;
            this.MenuOrientations = MenuOrientation.RightToLeft;
            this.BackgroundColor = Color.FromHex("#F0F0F0");
