### ISSUE TITLE
Keyboard Overlaps on Entry when using the MenuContainerPage

### ISSUE THREAD

**Issue by shubhambhosale** [XAM-Consulting/SlideOverKit#47]
I have added the MenuContainerPage on which we are using the Entry but when entry got the focus keyboard hide the entry in iOS. I also tried using the Xam.Plugins.Forms.KeyboardOverlap plugin, it only works when Page is inherited from ContentPage. So could you please help me to resolve the issue.

**Comment by jessejiang0214** [comment]
The reason of this because MenuContainerPageiOSRenderer inherits from PageRenderer and KeyboardOverlap inherits from PageRenderer too. If you install both of them, Xamarin can only choose one PageRenderer to render.

There is a solution, you can create your own page renderer inherits from KeyboardOverlapRenderer and implement the interface ISlideOverKitPageRendereriOS. So that you can use both of them. Please follow the sample https://github.com/XAM-Consulting/SlideOverKit/blob/master/SlideOverKitMoreSamples/iOS/Renderer/PageImpInterfaceRendereiOS.cs replace PageRenderer to KeyboardOverlapRenderer.

**Comment by shubhambhosale** [comment]
Thanks for your response. We have tried this & seems to be working fine.
